//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Restraunt_DB_Entities : DbContext
    {
        public Restraunt_DB_Entities()
            : base("name=Restraunt_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Dishes_Type> Dishes_Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Cards> Users_Cards { get; set; }
        public virtual DbSet<Users_Types> Users_Types { get; set; }
        public virtual DbSet<v_Dishes_With_Types_View> v_Dishes_With_Types_View { get; set; }
    }
}
