//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public System.DateTime Time { get; set; }
        public int dish_id { get; set; }
        public int user_id { get; set; }
        public bool IsOrdered { get; set; }
        public bool IsCooking { get; set; }
        public bool IsCooked { get; set; }
        public bool IsDelivered { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Users Users { get; set; }
    }
}
